library(shiny)
library(ggplot2)
library(reshape2)

shinyServer( function(input, output,session) {

    
    
    output$method <- renderText({
            paste( input$distriModel) 
        })
    
    
    output$confidenceInterval <- renderText({
        conf <- input$confInterval
        if(input$distriModel == "Binomial"){
            biEvents <- input$binomEvent
            biAll <- input$binomAll
            biPlot(biEvents, biAll, conf/100)
            model <- binom.test(biEvents, biAll, conf.level = conf/100)
            paste("Based on confidence. Low probability is ", round(model$conf.int[1], digits = 3),
                  ", most possible outcome under that probability is ", round(model$conf.int[1]*biAll),
                  "; High probability is ", round( model$conf.int[2], digits = 3 ), 
                  ", most possible outcome under that probability is ", round( model$conf.int[2]*biAll), 
                  "; And Sample estimate probability is ", round( model$estimate, digits = 3 ) ,
                  ", most possible outcome under that probability is ", round( model$estimate * biAll)
                  )
            
        }else if(input$distriModel == "Poisson"){
            poiEvents <- input$poissonEvent
            poiTime <- input$poissonTime
            model <- poisson.test(poiEvents, poiTime, conf.level = conf/100)
            paste("Based on confidence. Low lambda is ", round(model$conf.int[1], digits = 3),
                  ", most possible outcome under that lambda is ", round(model$conf.int[1] * poiTime),
                  "; High lambda is ", round( model$conf.int[2], digits = 3 ),
                  ", most possible outcome under that lambda is ", round( model$conf.int[2]*poiTime),
                  "; And Sample estimate lambda is ", round( model$estimate, digits = 3 ),
                      ", most possible outcome under that lambda is ", round( model$estimate*poiTime) )
            
        }
        
    })
    
    output$distributionConfig1<- renderUI(
        if(input$distriModel == "Binomial"){
            numericInput("binomAll","All number of observations", 50, min = 1)
        }else if(input$distriModel == "Poisson") {
            numericInput("poissonEvent", "Number of events happed",10, min = 1)
        }
    )
    
    output$config1Help <- renderUI(
        if(input$distriModel == "Binomial"){
            helpText("How many times the similar situations happens.")
        }else if(input$distriModel == "Poisson"){
            helpText("How many times certain events happens.")
        }
    )
    
    output$distributionConfig2 <- renderUI(
        
        if(input$distriModel == "Binomial"){
            numericInput("binomEvent","Number of events that happened", 10, min = 1)
        }else if(input$distriModel == "Poisson") {
            numericInput("poissonTime", "Elapsed Time units for events",50, min = 1)
        }
    )
    
    output$config2Help <- renderUI(
        if(input$distriModel == "Binomial"){
            helpText("How many times you experience a same result came up under certain situations")
        }else if(input$distriModel == "Poisson") {
            helpText("The elapsed time for the above events all happened.")
        }
    )
    
    output$disPlot <- renderPlot({
        conf <- input$confInterval
        if(input$distriModel == "Binomial"){
            biEvents <- input$binomEvent
            biAll <- input$binomAll
            biPlot(biEvents, biAll, conf/100)
        }else if(input$distriModel == "Poisson"){
            poiEvents <- input$poissonEvent
            poiTime <- input$poissonTime
            poiPlot(poiEvents, poiTime, conf/100)
        }
        
    })
    
    output$Explanation <- renderUI({
        str1 <- "<h3> Explanation <h3/>"
        body1 <- paste("The motivation of this application is to provide a clear way for users to 
          understanding how the confidence level works.")
        body2 <- "Depends on the input, this app would produce three density probability distribution graph.
        The middle one would be the density probability distribution based on sample estimate. 
        And the other two density graphes are generated based on the values generated by confidence level."
        HTML(paste(str1,body1,body2, sep = "<br/>"))
    })
    
    biPlot <- function( binomEvent,binomAll, confInt){
        bModel <- binom.test(binomEvent, binomAll, conf.level = confInt)
        #str(bModel)
        confRange <- bModel$conf.int
        
        x <- c(0:binomAll)
        lowRandom <- dbinom(x, binomAll, confRange[1])
        sampleRandom <- dbinom(x, binomAll, bModel$estimate)
        highRandom <- dbinom(x, binomAll, confRange[2])
        
        biDfLow <- data.frame(numberOfEventsHappens = x, probability = lowRandom, conf = "LowProb")
        biDfEst <- data.frame(numberOfEventsHappens=x, probability = sampleRandom, conf = "EstimateProb")
        biDfHigh <- data.frame( numberOfEventsHappens=x, probability = highRandom, conf="HighProb")
        biDf <- rbind(biDfLow, biDfEst, biDfHigh)
        
        ggplot(biDf, aes(x = numberOfEventsHappens, y = probability, colour = conf)) + geom_line()
    }
    
    poiPlot <- function(poiEvent, poiTime, confInt){
        pModel <- poisson.test(x = poiEvent, T= poiTime,conf.level = confInt )
        confRange <- pModel$conf.int
        
        x <- c(0:ifelse(poiEvent*2>poiTime, poiEvent*2, poiTime))
        lowDp <- dpois(x, confRange[1] * poiTime)
        estDp <- dpois(x, pModel$estimate * poiTime)
        highDp <- dpois(x, confRange[2] * poiTime)
        
        poiDfLow <- data.frame(numberOfEventsHappens =x , probability = lowDp, conf = "LowLambda")
        poiDfEst <- data.frame(numberOfEventsHappens =x, probability = estDp, conf = "EstLambda")
        poiDfHigh <- data.frame(numberOfEventsHappens = x, probability = highDp, conf = "HighLambda")
        poiDf <- rbind(poiDfLow, poiDfEst, poiDfHigh)
        
        ggplot(poiDf, aes(x =numberOfEventsHappens , y =probability, colour = conf)) + geom_line()
    }
    
    
} )